#!/usr/bin/env bash
#  a Bash script that configures a new Ubuntu machine to:
#	Install nginx on your server
#	Nginx should be listening on port 80
#	When querying Nginx at its root / with a GET request using curl,
#	it must return a page that contains the string Hello World!

# Update package lists and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Allow traffic from port 80
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page with the content "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Ensure nginx is configured to listen on port 80
# sudo sed -i 's/^\s*listen\s*\(.*\);/listen 80;/' /etc/nginx/sites-available/default

sudo service nginx restart
